{ config, lib, pkgs, ... }:

with lib;

{
  options.djh.tridactyl = {
    enable = mkEnableOption "Tridactyl browser extension configuration";
    
    colorScheme = mkOption {
      type = types.str;
      default = "catppuccin";
      description = "Color scheme for Tridactyl";
    };
    
    customCss = mkOption {
      type = types.str;
      default = "https://raw.githubusercontent.com/DanielHatakeyama/catppuccin-tridactyl/main/catppuccin.css";
      description = "Custom CSS URL for Tridactyl theming";
    };

    enableYouTubeKeybinds = mkOption {
      type = types.bool;
      default = false;
      description = "Enable YouTube-specific keybindings (commented out by default)";
    };

    extraConfig = mkOption {
      type = types.lines;
      default = "";
      description = "Additional Tridactyl configuration";
    };
  };

  config = mkIf config.djh.tridactyl.enable {
    # Create the tridactylrc configuration file
    home.file.".config/tridactyl/tridactylrc".text = ''
      " Tridactyl Configuration - Generated by Home Manager
      " Based on your archive config: dotfiles-mac-wk/tridactyl/tridactylrc

      " Set the color scheme with custom CSS
      colourscheme --url ${config.djh.tridactyl.customCss} ${config.djh.tridactyl.colorScheme}

      " Toggle into ignore mode with Ctrl-Delete
      bind <C-Delete> mode ignore

      " While in ignore mode, Ctrl-Delete returns you to normal
      bind --mode=ignore <C-Delete> mode normal

      " Allow ':' to open the command line even when in ignore mode
      bind --mode=ignore : fillcmdline_notrail

      ${optionalString config.djh.tridactyl.enableYouTubeKeybinds ''
      " YouTube-specific keybindings
      " Template for YouTube-specific keybinds:
      " bind --mode=normal --urls="^(https?://)?(www\.)?youtube\.com" <key> <command>

      " YouTube Keybinds:
      bind --mode=normal --urls="^(https?://)?(www\.)?youtube\.com" h composite js -p document.querySelector('video')?.currentTime -= 10
      bind --mode=normal --urls="^(https?://)?(www\.)?youtube\.com" l composite js -p document.querySelector('video')?.currentTime += 10
      bind --mode=normal --urls="^(https?://)?(www\.)?youtube\.com" > composite mode ignore | keyfeed > | mode normal
      bind --mode=normal --urls="^(https?://)?(www\.)?youtube\.com" < composite mode ignore | keyfeed < | mode normal
      ''}

      ${config.djh.tridactyl.extraConfig}
    '';
  };
}
